// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SrmCreditEngine.Infrastructure.Data;

#nullable disable

namespace SrmCreditEngine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("credit")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Cedent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cedents");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_cedents_cnpj");

                    b.ToTable("cedents", "credit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Cnpj = "12345678000199",
                            ContactEmail = "ops@srmasset.com.br",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "SRM Asset Management LTDA",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code");

                    b.ToTable("currencies", "credit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Code = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "Real Brasileiro",
                            Symbol = "R$",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Code = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "US Dollar",
                            Symbol = "$",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_date");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rates");

                    b.HasIndex("ToCurrencyId")
                        .HasDatabaseName("ix_exchange_rates_to_currency_id");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId", "EffectiveDate")
                        .HasDatabaseName("ix_exchange_rates_pair_date");

                    b.ToTable("exchange_rates", "credit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromCurrencyId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Rate = 5.75m,
                            Source = "SEED",
                            ToCurrencyId = new Guid("11111111-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Receivable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CedentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cedent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_number");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_date");

                    b.Property<int>("FaceCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("face_currency");

                    b.Property<decimal>("FaceValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("face_value");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_receivables");

                    b.HasIndex("CedentId")
                        .HasDatabaseName("ix_receivables_cedent_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_receivables_due_date");

                    b.HasIndex("DocumentNumber", "CedentId")
                        .IsUnique()
                        .HasDatabaseName("ix_receivables_doc_cedent");

                    b.ToTable("receivables", "credit");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AppliedSpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("applied_spread");

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("base_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("discount");

                    b.Property<decimal>("ExchangeRateApplied")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate_applied");

                    b.Property<int>("FaceCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("face_currency");

                    b.Property<decimal>("FaceValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("face_value");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<decimal>("NetDisbursement")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("net_disbursement");

                    b.Property<int>("PaymentCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("payment_currency");

                    b.Property<decimal>("PresentValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("present_value");

                    b.Property<Guid>("ReceivableId")
                        .HasColumnType("uuid")
                        .HasColumnName("receivable_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("settled_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TermInMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_in_months");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_settlements");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_settlements_created_at");

                    b.HasIndex("PaymentCurrency")
                        .HasDatabaseName("ix_settlements_payment_currency");

                    b.HasIndex("ReceivableId")
                        .IsUnique()
                        .HasDatabaseName("ix_settlements_receivable_id");

                    b.HasIndex("SettledAt")
                        .HasDatabaseName("ix_settlements_settled_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_settlements_status");

                    b.ToTable("settlements", "credit");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("SrmCreditEngine.Domain.Entities.Currency", "FromCurrency")
                        .WithMany("ExchangeRatesFrom")
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rates_currencies_from_currency_id");

                    b.HasOne("SrmCreditEngine.Domain.Entities.Currency", "ToCurrency")
                        .WithMany("ExchangeRatesTo")
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exchange_rates_currencies_to_currency_id");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Receivable", b =>
                {
                    b.HasOne("SrmCreditEngine.Domain.Entities.Cedent", "Cedent")
                        .WithMany("Receivables")
                        .HasForeignKey("CedentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receivables_cedents_cedent_id");

                    b.Navigation("Cedent");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("SrmCreditEngine.Domain.Entities.Receivable", "Receivable")
                        .WithOne("Settlement")
                        .HasForeignKey("SrmCreditEngine.Domain.Entities.Settlement", "ReceivableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_receivables_receivable_id");

                    b.Navigation("Receivable");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Cedent", b =>
                {
                    b.Navigation("Receivables");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Currency", b =>
                {
                    b.Navigation("ExchangeRatesFrom");

                    b.Navigation("ExchangeRatesTo");
                });

            modelBuilder.Entity("SrmCreditEngine.Domain.Entities.Receivable", b =>
                {
                    b.Navigation("Settlement");
                });
#pragma warning restore 612, 618
        }
    }
}
